---
- name: Playbook for creating users
  hosts: all
  become: yes

  tasks:
  - name: Create users
    user:
     name: somesh
     home: /home/somesh
     shell: /bin/bash
     state: present
