---
- name: Create a cron job
  hosts: all

  tasks:
    - name: Copying file 
      become: true
      copy:
        src: cfile.sh
        dest: /home/somesh
        owner: somesh
        group: somesh
        mode: 0644

    - name: Schedule cron
      cron:
        name: This job is scheduled by Ansible
        minute: "0"
        hour: "10"
        day: "*"
        month: "*"
        weekday: "4"
        user: somesh
        job: "/home/somesh/cfile.sh"
