---
- name: Create users thru loop
  hosts: all

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - jerry
        - kramer
        - eliane
