---
- name: Create users thru loop
  hosts: all
  become: true
  vars:
    users: [jerry, kramer, eliane]

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop: "{{ users }}"
