---
- name: Allow HTTP traffic with UFW
  hosts: all
  become: true

  tasks:
    - name: Ensure ufw is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: true

    - name: Allow OpenSSH through firewall
      ansible.builtin.command: ufw allow OpenSSH
      register: ufw_ssh_rule
      changed_when: "'Skipping adding existing rule' not in ufw_ssh_rule.stdout"

    - name: Open port for http
      ansible.builtin.command: ufw allow Apache
      register: ufw_http_rule
      changed_when: "'Skipping adding existing rule' not in ufw_http_rule.stdout"
      notify:
        - Reload ufw

    - name: Ensure ufw is enabled
      ansible.builtin.command: ufw --force enable
      register: ufw_enable
      changed_when: "'already enabled' not in ufw_enable.stdout"

  handlers:
    - name: Reload ufw
      ansible.builtin.command: ufw reload
