---
- name: Install and start Nginx
  hosts: all
  become: yes

  tasks:
    - name: Install nginx package
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Ensure nginx service is enabled and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Open port 80 for http access
      firewalld:
        service: http
        permanent: true
        state: enabled

    - name: Restart firewalld service to load firewall changes
      service:
        name: firewalld
        state: reloaded
